trigger:
  branches:
    include:
    - master
variables:
  goVersion: '1.15.2'
  projectName: 'totp'
pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: GoTool@0
  displayName: 'Use Go ${{ variables.goVersion }}'
  inputs:
    version: ${{ variables.goVersion }}

- task: Go@0
  displayName: 'Build Application Binary For MacOS'
  env:
    CGO_ENABLED: 0
    GOOS: darwin
    GOARCH: amd64
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '-o $(Build.ArtifactStagingDirectory)/${{variables.projectName}}_osx'
- task: Go@0
  displayName: 'Build Application Binary For Linux'
  env:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '-o $(Build.ArtifactStagingDirectory)/${{variables.projectName}}_linux' 
- task: Go@0
  displayName: 'Build Application Binary For Windows'
  env:
    CGO_ENABLED: 0
    GOOS: windows
    GOARCH: amd64
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
    arguments: '-o $(Build.ArtifactStagingDirectory)/${{variables.projectName}}_windows.exe'       
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: 'github.com_chujieyang'
    repositoryName: 'chujieyang/totp'
    tagSource: manual
    tag: $(Build.BuildNumber)
    assets: $(Build.ArtifactStagingDirectory)/*
